### ISSUE TITLE
Add Support for vRA8

### ISSUE THREAD

**Issue by kclinden** [test-kitchen/kitchen-vra#34]
### Versions:
All Versions of kitchen-vra

### Platform Details

* Version of vRA: 8.0
* Version of ESXi: 6.7 U3

### Scenario:

Add the same capability but for vRA 8. This may need to be a different driver due to the significant changes in vRA

### Expected Result:

Kitchen vRA driver will be able to deploy blueprints from vRA 8

**Comment by vkarve-chef** [comment]
- vRA version indicator is added in kitchen configuration, if needed
- Use of vmware-vra-gem is updated to support vRA 8.x
- Backward compatibility is maintained for vRA 7.x
- Tests are updated to cover code changes

**Comment by vkarve-chef** [comment]
@kclinden could you please try out the latest kitchen-vra plugin version and mark the issue as Closed it works for you on vRA8? you can refer the updated driver documentation at [kitchen.ci](https://kitchen.ci/docs/drivers/vra/)
